### ISSUE TITLE
Invalid Logic

### ISSUE THREAD

**Issue by davidlawn** [agapoff/check_kubernetes#15]
https://github.com/agapoff/check_kubernetes/blob/aaf18a323264a81b71372bf1be1763d99f3752c7/check_kubernetes.sh#L690-L695

As you check Warning first the service will never respond with CRITICAL unless Warning is greater than Critical.

Check if the Critical threshold has been passed first and only if it has not then check if the Warning threshold has been passed.

**Comment by agapoff** [comment]
Thank you. The issue has been fixed.
