### ISSUE TITLE
Incorrect resource type 'pvs'

### ISSUE THREAD

**Issue by robertpenberthy** [agapoff/check_kubernetes#20]
https://github.com/agapoff/check_kubernetes/blob/405ff6be9fc25db8e2b38599a734a0a7e78be57b/check_kubernetes.sh#L230

When the script runs `get pvs` it responds with `error: the server doesn't have a resource type "pvs"`.  I believe it should either be `get pv` or `get pvc` depending on if it's checking the persistent volumes or persistent volume claims.

I'm on kubernetes 1.18, in case the version of kubernetes matters.

**Comment by agapoff** [comment]
Thank you.
Should be fixed in 
https://github.com/agapoff/check_kubernetes/commit/a034811c52ae64b5508a82162ae1d553d70e632c
